## Challenge
Gunakan dataset publik apa saja (misalnya data CSV penjualan atau Titanic), lalu hitung rata-rata nilai pada kolom numerik berdasarkan kategori tertentu menggunakan metode ```.groupby()```.

### Import Library

In [45]:
import pandas as pd
import numpy as np
"""
Membutuhkan Library Kagglehub karena kita menggunakan kernel dari google colab.
Oleh karena itu untuk bisa mengakses dataset dari platform kaggle kita harus
download datasetnya lewat library kagglehub.
"""
import kagglehub

In [52]:
path = kagglehub.dataset_download("heptapod/titanic")
path

Using Colab cache for faster access to the 'titanic' dataset.

'/kaggle/input/titanic'

In [195]:

df = pd.read_csv("/kaggle/input/titanic/train_and_test2.csv")
df.head(10)

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
5,6,28.0,8.4583,0,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
6,7,54.0,51.8625,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
7,8,2.0,21.0750,0,3,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
8,9,27.0,11.1333,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
9,10,14.0,30.0708,1,1,0,0,0,0,0,...,0,0,0,2,0,0,0.0,0,0,1

In [203]:
df_new = df.copy()
df_group = df_new.groupby(by="Age")["Fare"].mean().reset_index()
df_group.head(10)

    Age       Fare
0  0.17  20.575000
1  0.33  14.400000
2  0.42   8.516700
3  0.67  14.500000
4  0.75  17.430533
5  0.83  19.033333
6  0.92  89.650000
7  1.00  28.050420
8  2.00  34.881250
9  3.00  24.066671